[package]
name = "solcon_testcase"
version = "0.1.0"
edition = "2021"

[dependencies]
testcase_anothercrate = { path = "../testcaseanother" }
testcase_mutex_dyn_type = { path = "../testcase_mutex_dyn_type" }